# PAM API Message Size Configuration
# This file defines size limits for different types of messages in the PAM system

# Global Settings
global:
  enable_size_validation: true
  enable_field_validation: true
  enable_statistics_tracking: true
  auto_cleanup_interval: 3600  # seconds

# Message Type Limits (in bytes)
message_type_limits:
  websocket_text: 65536      # 64KB - WebSocket text messages
  websocket_json: 131072     # 128KB - WebSocket JSON messages
  rest_api_chat: 32768       # 32KB - REST API chat messages
  voice_synthesis: 10240     # 10KB - Voice synthesis text
  feedback: 4096             # 4KB - Feedback submissions
  file_upload: 10485760      # 10MB - File uploads
  attachment: 5242880        # 5MB - Attachment references
  context_data: 16384        # 16KB - Context/metadata

# Character Limits for Text Content
character_limits:
  websocket_text: 10000      # 10K characters
  rest_api_chat: 5000        # 5K characters
  voice_synthesis: 2000      # 2K characters (reasonable for TTS)
  feedback: 1000             # 1K characters
  context_data: 2000         # 2K characters

# Field-Specific Limits (in characters)
field_limits:
  message: 5000              # Main message content
  content: 5000              # Alternative message field
  title: 200                 # Titles and subjects
  description: 1000          # Descriptions
  feedback_text: 1000        # Feedback text
  user_id: 100               # User identifiers
  session_id: 100            # Session identifiers
  filename: 255              # File names
  url: 2048                  # URLs and links
  email: 254                 # Email addresses
  phone: 20                  # Phone numbers
  name: 100                  # Names
  address: 500               # Addresses

# Security Settings
security:
  immediate_disconnect_threshold: 1048576  # 1MB - immediately disconnect for messages this large
  log_violations: true
  block_after_violations: 5               # Block user after this many violations
  violation_tracking_window: 3600         # Track violations for this many seconds

# Performance Settings
performance:
  validation_timeout: 5.0     # seconds
  max_nested_depth: 10        # Maximum depth for nested structures
  compression_check: false    # Check if message could be compressed (expensive)

# User Experience Settings
user_experience:
  provide_detailed_errors: true
  suggest_size_reduction: true
  show_size_in_errors: true
  format_sizes_human_readable: true

# Monitoring Settings
monitoring:
  track_validation_performance: true
  log_large_messages: true
  alert_on_high_violation_rate: true
  violation_rate_threshold: 0.1  # 10% violation rate triggers alert

# Development Settings (only in dev environment)
development:
  allow_oversized_messages: false
  log_all_validations: false
  detailed_field_analysis: true
  test_mode_overrides: false