#!/bin/bash
echo "🔍 Checking PAM performance in backend logs..."
echo ""
echo "Recent PAM chat requests (last 20 lines):"
echo "Note: You'll need to check Render dashboard for actual logs"
echo ""
echo "Expected improvements:"
echo "  ✅ Response time: <3 seconds (was 63s)"
echo "  ✅ Safety layer: Regex-only (<1ms, was 133ms)"
echo "  ✅ Tool prefiltering: Supporting both formats"
echo "  ✅ Claude Sonnet 4.5: Primary AI responding"
echo ""
echo "To verify:"
echo "1. Visit Render dashboard: https://dashboard.render.com"
echo "2. Go to wheels-wins-backend-staging service"
echo "3. Click 'Logs' tab"
echo "4. Search for: 'PAM chat'"
echo "5. Check response times in logs"
