# Netlify Staging Configuration

[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.17.0"
  VITE_ENVIRONMENT = "staging"

[[redirects]]
  from = "/api/*"
  to = "https://wheels-wins-backend-staging.onrender.com/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(self), geolocation=(self)"

[context.staging]
  environment = { VITE_ENVIRONMENT = "staging" }