# Staging-specific Netlify configuration
[build]
  publish = "dist" 
  command = "npm run build:staging"

[build.environment]
  NODE_VERSION = "20"
  # Staging-specific environment
  VITE_ENVIRONMENT = "staging"
  VITE_SHOW_STAGING_BANNER = "true"
  # Disable secrets scanning for staging
  SECRETS_SCAN_ENABLED = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers (less strict for staging)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Allow staging backend connections
    Content-Security-Policy = "default-src 'self' https: data: blob: 'unsafe-inline' 'unsafe-eval'; img-src 'self' https: data: blob:; font-src 'self' https: data:; connect-src 'self' https: wss: wss://wheels-wins-backend-staging.onrender.com wss://pam-backend.onrender.com;"
    X-Robots-Tag = "noindex, nofollow"  # Don't index staging site

# Performance headers for static assets
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=3600, must-revalidate"
    
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=3600, must-revalidate"
