services:
  - type: web
    name: pam-web
    env: docker
    plan: standard
    dockerfilePath: ./backend/Dockerfile
    dockerContext: .
    autoDeploy: true
    envVars:
      - key: PORT
        value: "10000"
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: SENTRY_DSN
        sync: false
    healthCheckPath: /health
    disk:
      name: cache
      mountPath: /cache
      sizeGB: 1
  - type: worker
    name: pam-celery
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: .
    command: >
      celery -A app.tasks.celery_worker worker
      --loglevel=info
      --logfile=/var/log/celery/worker.log
    envVars:
      - fromService:
          type: web
          name: pam-web
          envVarKey: REDIS_URL
