services:
  - type: web
    name: pam-backend
    env: python
    plan: free
    runtime: python-3.12.7
    buildCommand: pip install -r pam-backend/requirements.txt
    startCommand: bash -c "cd pam-backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: OPENAI_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: REDIS_URL
        fromService:
          type: redis
          name: pam-redis
          property: connectionString
      - key: GOOGLE_API_KEY
        fromService: null   # mark Secret in dashboard
    autoDeploy: true

  - type: redis
    name: pam-redis
    plan: free
    ipAllowList: []
EOF