services:
  - type: web
    name: pam-backend
    env: docker
    plan: free
    dockerfilePath: pam-backend/Dockerfile
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: OPENAI_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: REDIS_URL
        fromService:
          type: redis
          name: pam-redis
          property: connectionString
      - key: GOOGLE_API_KEY
        fromService: null  # mark Secret in dashboard
    autoDeploy: true

  - type: redis
    name: pam-redis
    plan: free
    ipAllowList: []
