services:
  - name: web
    type: web
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - fromGroup: wheels-env
  - name: worker
    type: worker
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    autoDeploy: true
    startCommand: celery -A app.celery_app worker --loglevel=info
    envVars:
      - fromGroup: wheels-env
