# Data Source Configuration
# API keys, authentication, and source-specific settings

# API Keys and Authentication (set these in environment variables or .env file)
api_keys:
  # Government APIs
  nps_api_key: "${NPS_API_KEY}"  # National Park Service (US)
  parks_canada_key: "${PARKS_CANADA_KEY}"
  recreation_gov_key: "${RECREATION_GOV_KEY}"
  
  # Commercial APIs
  google_places_key: "${GOOGLE_PLACES_KEY}"
  google_maps_key: "${GOOGLE_MAPS_KEY}"
  tripadvisor_key: "${TRIPADVISOR_KEY}"
  
  # AI Enhancement
  openai_key: "${OPENAI_API_KEY}"
  
  # Database
  supabase_url: "${SUPABASE_URL}"
  supabase_key: "${SUPABASE_KEY}"

# Rate Limiting Configuration
rate_limits:
  default: 60  # requests per hour
  government_apis: 100
  commercial_apis: 50
  scraping: 30
  wikipedia: 100
  
  # Delays between requests (seconds)
  min_delay: 1
  max_delay: 5
  backoff_multiplier: 2

# Data Source Priorities and Reliability Scores
source_reliability:
  government_apis: 10      # Highest reliability
  wikipedia: 9
  tourism_boards: 8
  commercial_apis: 7
  verified_scraping: 6
  community_data: 5
  unverified_scraping: 3   # Lowest reliability

# Wikipedia Configuration
wikipedia:
  languages: ["en"]
  extract_length: 500
  image_count: 3
  search_radius_km: 50
  categories:
    - "National parks"
    - "State parks"
    - "Provincial parks"
    - "Protected areas"
    - "Camping"
    - "Tourist attractions"
    - "Waterfalls"
    - "Beaches"
    - "Lakes"
    - "Swimming"

# Google Places API Configuration
google_places:
  search_types:
    - "tourist_attraction"
    - "natural_feature"
    - "park"
    - "campground"
    - "rv_park"
    - "establishment"
  search_radius: 50000  # 50km
  max_results_per_search: 60

# Data Processing Configuration
processing:
  # Duplicate detection
  duplicate_threshold_meters: 500  # Locations within 500m considered duplicates
  
  # Data validation
  required_fields:
    - name
    - latitude
    - longitude
    - country
  
  # Text enhancement
  ai_enhancement:
    enabled: true
    description_max_length: 300
    generate_missing_descriptions: true
    enhance_existing_descriptions: false
  
  # Image processing
  images:
    download_images: false  # Just collect URLs for now
    max_images_per_location: 5
    preferred_image_size: "large"

# Output Configuration
output:
  formats:
    - "json"
    - "csv"
    - "sql"
  
  # File organization
  organize_by_country: true
  organize_by_type: true
  
  # Database upload settings
  batch_size: 100
  test_mode: true  # Start with test uploads first
  
  # Data validation before upload
  validate_coordinates: true
  validate_required_fields: true
  check_for_duplicates: true

# Logging Configuration
logging:
  level: "INFO"
  file_rotation: "100 MB"
  retention: "30 days"
  
  # Log categories
  categories:
    - "scraping"
    - "api_calls"
    - "data_processing"
    - "validation"
    - "database"
    - "errors"

# Safety and Ethics
safety:
  # Scraping ethics
  respect_robots_txt: true
  user_agent: "Wheels&Wins-DataCollector/1.0 (Travel Data Aggregation)"
  
  # Rate limiting enforcement
  enforce_rate_limits: true
  respect_retry_after: true
  
  # Data ethics
  exclude_private_property: true
  exclude_restricted_areas: true
  verify_public_access: true

# Progress Tracking
progress:
  checkpoint_interval: 100  # Save progress every 100 records
  resume_from_checkpoint: true
  progress_file: "data/progress.json"
  
  # Monitoring
  log_progress_every: 50
  estimate_completion_time: true