# Render configuration for autonomous data collector
# This runs independently as a cron job, collecting travel data monthly

services:
  - type: cron
    name: wheels-wins-data-collector
    runtime: python
    repo: https://github.com/yourusername/wheels-wins-landing-page
    rootDir: wheels-wins-data-collector
    buildCommand: pip install -r requirements.txt
    
    # Run every Sunday at 2 AM UTC (weekly collection)
    schedule: "0 2 * * 0"
    
    # Main collection command (autonomous collector)
    command: python main_autonomous.py
    
    # Environment variables
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: NPS_API_KEY
        sync: false
      - key: RECREATION_GOV_KEY
        sync: false
      - key: GOOGLE_PLACES_KEY
        sync: false
      - key: COLLECTOR_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11
    
    # Health check
    healthCheckPath: /health
    
    # Notifications
    notificationEmail: your-email@example.com