"""Social Tools Constants

Default values and limits for social features
"""

DEFAULT_FEED_LIMIT = 20
DEFAULT_SEARCH_LIMIT = 20
DEFAULT_NEARBY_LIMIT = 20
DEFAULT_NEARBY_RADIUS_MILES = 50
DEFAULT_LOCATION_SHARE_DURATION_HOURS = 24

LATITUDE_MIN = -90
LATITUDE_MAX = 90
LONGITUDE_MIN = -180
LONGITUDE_MAX = 180
