name: Database Health Check

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:  # Allow manual triggering
  pull_request:
    paths:
      - 'supabase/migrations/**'
      - 'backend/app/models/**'

jobs:
  check-database-health:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install asyncpg python-dotenv
    
    - name: Run database health check
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        python backend/scripts/check_database_health.py
    
    - name: Create issue if problems found
      if: failure()
      uses: actions/github-script@v6
      with:
        script: |
          const title = `Database Health Check Failed - ${new Date().toISOString().split('T')[0]}`;
          const body = `The automated database health check found issues that need attention:
          
          - Missing indexes on foreign keys
          - Tables with high dead row percentage
          - Slow queries
          - Unused indexes
          
          Please run \`python backend/scripts/check_database_health.py\` locally for details.
          
          [View workflow run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})`;
          
          // Check if issue already exists
          const issues = await github.rest.issues.listForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: ['database-health', 'automated'],
            state: 'open'
          });
          
          if (issues.data.length === 0) {
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: title,
              body: body,
              labels: ['database-health', 'automated', 'performance']
            });
          }