name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allow manual deployment

jobs:
  production-deploy:
    runs-on: ubuntu-latest
    environment: production  # Requires approval for production deployments
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run full quality checks
      run: npm run quality:check:full
      
    - name: Security audit
      run: npm run security:audit
      
    - name: Build for production
      run: npm run build:production
      env:
        VITE_ENVIRONMENT: production
        VITE_SUPABASE_URL: ${{ secrets.PRODUCTION_SUPABASE_URL }}
        VITE_SUPABASE_ANON_KEY: ${{ secrets.PRODUCTION_SUPABASE_ANON_KEY }}
        VITE_API_BASE_URL: ${{ secrets.PRODUCTION_API_BASE_URL }}
        VITE_MAPBOX_ACCESS_TOKEN: ${{ secrets.PRODUCTION_MAPBOX_TOKEN }}
        VITE_STRIPE_PUBLISHABLE_KEY: ${{ secrets.PRODUCTION_STRIPE_PUBLISHABLE_KEY }}
        VITE_GOOGLE_ANALYTICS_ID: ${{ secrets.PRODUCTION_GOOGLE_ANALYTICS_ID }}
        VITE_SENTRY_DSN: ${{ secrets.PRODUCTION_SENTRY_DSN }}
        VITE_SHOW_STAGING_BANNER: false
        VITE_ENABLE_BETA_FEATURES: false
        VITE_ENABLE_DEBUG_TOOLS: false
        VITE_ENABLE_TEST_DATA: false
        VITE_ENABLE_PERFORMANCE_MONITORING: true
        VITE_ENABLE_STRICT_CSP: true
        
    - name: Deploy to Netlify Production
      uses: nwtgck/actions-netlify@v3.0
      with:
        publish-dir: './dist'
        production-deploy: true
        github-token: ${{ secrets.GITHUB_TOKEN }}
        deploy-message: "Production deploy - ${{ github.sha }}"
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_PRODUCTION_SITE_ID }}
        
    - name: Notify deployment success
      if: success()
      uses: actions/github-script@v7
      with:
        script: |
          const deployUrl = "https://your-production-domain.com";
          console.log(`✅ Production deployment successful: ${deployUrl}`);
          
    - name: Notify deployment failure
      if: failure()
      uses: actions/github-script@v7
      with:
        script: |
          console.log("❌ Production deployment failed!");
          // You could add Slack/Discord notifications here